### ISSUE TITLE
calc outputs `Instance of 'CoverageResult'`

### ISSUE THREAD

**Issue by bgourlie** [Adracus/dart-coveralls#17]
Running calc outputs `Instance of 'CoverageResult'`.  Presumably, `CoverageResult` should override toString().

**Comment by Adracus** [comment]
Fixed in 561bd161797d28df11dc1eb58c84dbbf54d71451

**Comment by danschultz** [comment]
I'm still having this issue with v0.1.10

**Comment by Adracus** [comment]
Finally resolved the issue, sorry for that dumb error
