### ISSUE TITLE
Support for files outside of /lib.

### ISSUE THREAD

**Issue by gjersvik** [Adracus/dart-coveralls#19]
When looking at the code it seems --exclude-test-files trows out the baby with the bath by excluding any and all local files. This create a nasty scenario when the files under test is in /bin.

It seems by the coding of dart-coveralls that there is an assumption built in that only files inside /lib will ever need to be tested and yes that work for most packages bot not applications.

If support is not added i hope this issue stands as a warning to others. As it sands if you want to test files outside /lib don't enable --exclude-test-files that every tutorial say.

**Comment by Adracus** [comment]
In the last commit, I added a better filtering of the dart files. I will push it to pub as soon as I got enough tests.
