### ISSUE TITLE
Feature request: Let me give dart_coverall list of observatory urls.

### ISSUE THREAD

**Issue by gjersvik** [Adracus/dart-coveralls#20]
It would be nice if i could give dart_coverall a list of urls to existing observatory's that is paused. So that dart_coverall can extract and combine coverage information. This would enable exacting coverage information from Dartium. And allow more complex setups where no single test run can cover it all.

Yes dart_coverall should unpause when done.

**Comment by Adracus** [comment]
It would be quite nice, but currently I'm involved with several other projects. If you implement the feature by yourself and send a pull request, I'll have a look at it and merge it if it's okay. In the near future I won't implement this.
